//Evaluacion
alert("Luis Alberto Suarez");


// Digite su Nombre y Edad.

var nombre = parseInt(prompt("Digite su nombre"));
alert("Luis Alberto Suarez");

var  edad = parseInt(prompt("Digite su edad"));
while (edad > 1 || edad < 120);
    

    // Operaciones basicas

    var operacion = prompt(`Digite la operacion:
    1.suma
    2.resta
    3.multiplicacion
    4.Division`);

    var suma1 = prompt("Digita la cantidad");
  



    

